### ISSUE TITLE
When restarting the bot and leaving Lavalink running it wont reconnect to the old player

### ISSUE THREAD

**Issue by JoniXTech** [shipgirlproject/Shoukaku#118]
When you try to leave Lavalink running (with a player running) and restart the bot, it won't reconnect to the player that is running rather create a new one. So the old player which is running cant be controlled anymore until it has a timeout.

Would it be possible to reconnect to the old player and control it again?

**Comment by Deivu** [comment]
You need to create your own resuming system in this case, you need to "redo the players as they are" before you shutdown your bot, save it somewhere (database, file, or redis, your choice), then before shoukaku connects, you need to populate the players per node manually by creating it from the data you saved
