### ISSUE TITLE
Update deprecated playing options

### ISSUE THREAD

**Issue by Fyphen1223** [shipgirlproject/Shoukaku#168]
not encodedTrack option in play or some other methods, use this instead.
encodedTrack is deprecated.

```
track: {
  encoded: ...
}
```

**Comment by Deivu** [comment]
Feel free to try the latest commit and check if this fixes the issue

**Comment by emirkabal** [comment]
> Feel free to try the latest commit and check if this fixes the issue

when will you publish it

**Comment by Deivu** [comment]
> > Feel free to try the latest commit and check if this fixes the issue
> 
> when will you publish it?

After it was tested throughly, it should be on `master` branch right now which you can install
