### ISSUE TITLE
Error at Nodes.Name

### ISSUE THREAD

**Issue by AlfianRafli** [shipgirlproject/Shoukaku#169]
everything is correct but there is an error like this. why is that?
![Screenshot_20240101-141030](https://github.com/shipgirlproject/Shoukaku/assets/124662982/d440341e-c645-4bc9-9600-a64928aa7e84)

**Comment by thaddeuskkr** [comment]
if this happens to still be an issue, you need to give more information than that - e.g. the code that you're trying to run.

though from that error message it seems to be that you did not handle shoukaku's error event (which you should - as stated by [this section](https://github.com/shipgirlproject/Shoukaku?tab=readme-ov-file#small-code-snippet-examples) of the readme.
```js
// ALWAYS handle error, logging it will do
shoukaku.on("error", (_, error) => console.error(error));
```
