### ISSUE TITLE
Shoukaku client is sending the request but no audio will be played

### ISSUE THREAD

**Issue by Fyphen1223** [shipgirlproject/Shoukaku#172]
No error, it just doesn't play any sounds.
Here is the reference: https://github.com/lavalink-devs/Lavalink/discussions/1025

**Comment by Gpcodez** [comment]
Same issue

**Comment by Deivu** [comment]
Check latest commits and see if this fixes yoru issues

**Comment by Fyphen1223** [comment]
> Check latest commits and see if this fixes your issues

Thanks! I'll check it out as soon as possible!

**Comment by Fyphen1223** [comment]
@Deivu I don't think the latest commit fixed the issue...
I'm still having the same issue.

**Comment by flav-code** [comment]
Fixed for me

**Comment by 0t4u** [comment]
Please create a new issue if this is still a problem.
