### ISSUE TITLE
Track ending event

### ISSUE THREAD

**Issue by ziberex** [shipgirlproject/Shoukaku#173]
Is there any way to handle track ending event in shuokaku library except setting a timeout and then leaving voice channel like it shows in https://www.npmjs.com/package/shoukaku?

**Comment by karyeet** [comment]
You handle it however you want... maybe play another track

**Comment by Deivu** [comment]
There's an example bot at the bottom of the README.md (Implementations) if you are reading the whole file, which is a **complete** implementation of the library. 

The examples are just small snippets that lets you show how technically  it can work
