### ISSUE TITLE
.playTrack() will not change the boolean value of .paused in v4.0.1

### ISSUE THREAD

**Issue by blackink7777** [shipgirlproject/Shoukaku#175]
**I don't know if this is a logic error on my part or a bug haha**            

When I was making a function to determine whether to stop music, 
I accidentally discovered that after I used the `.setPaused(true)` function, 
I directly used the`.playTrack(options: {noReplace: false})`  function to play new music **(that is, I would Replace the current music and play),** 
at this point I use the .paused logic to determine if the music is not playing and will return a true value, but this is obviously wrong.

```javascript
await this.connection[guildId].playTrack({
    track: result.data.encoded,
    options: {
         volume: 20,
         noReplace: false
    }
});
console.log(this.connection[guildId]?.paused) // return: false
this.connection[guildId].setPaused(true)
console.log(this.connection[guildId]?.paused) // return: true
await this.connection[guildId].playTrack({
    track: result.data.encoded,
    options: {
         volume: 20,
         noReplace: false
    }
});
console.log(this.connection[guildId]?.paused) // return: true
```

If the problem is solved please remember to remind me, love you :>

**Comment by Deivu** [comment]
See latest commits and see if this fixes your issue

**Comment by 0t4u** [comment]
PR merged
