### ISSUE TITLE
emit

### ISSUE THREAD

**Issue by LucasB25** [shipgirlproject/Shoukaku#179]
Since your last commit, emit returns errors
![image](https://github.com/shipgirlproject/Shoukaku/assets/50886682/f42347d6-43ae-4ce9-b373-511e90328055)
![image](https://github.com/shipgirlproject/Shoukaku/assets/50886682/0ed94782-1868-4fba-9630-6b8d38901ebd)

**Comment by 0t4u** [comment]
reverted problematic commit

**Comment by EvilG-MC** [comment]
I'm really sorry, I missed the `emit`... I'll fix it when I can.

**Comment by LucasB25** [comment]
> I'm really sorry, I missed the `emit`... I'll fix it when I can.

I do not understand despite your reverse I still have this error after updating the files

**Comment by 0t4u** [comment]
> > I'm really sorry, I missed the `emit`... I'll fix it when I can.
> 
> I do not understand despite your reverse I still have this error after updating the files

Try installing using your package manager again, or delete node_modules and install dependencies again?

**Comment by LucasB25** [comment]
> > > I'm really sorry, I missed the `emit`... I'll fix it when I can.
> > 
> > 
> > I do not understand despite your reverse I still have this error after updating the files
> 
> Try installing using your package manager again, or delete node_modules and install dependencies again?



> > > I'm really sorry, I missed the `emit`... I'll fix it when I can.
> > 
> > 
> > I do not understand despite your reverse I still have this error after updating the files
> 
> Try installing using your package manager again, or delete node_modules and install dependencies again?

that’s exactly what I did

**Comment by LucasB25** [comment]
https://github.com/appujet/lavamusic
Many of my stop not this complaining about this concern on Lavamusic, if you want to look for yourself
But I tested with 
- `npm update' not working
- delete "node_modules" and "package-lock.json" + `npm i` not working

**Comment by 0t4u** [comment]
> [appujet/lavamusic](https://github.com/appujet/lavamusic) Many of my stop not this complaining about this concern on Lavamusic, if you want to look for yourself But I tested with
> 
>     * `npm update` not working
> 
>     * delete "node_modules" and "package-lock.json" + `npm i` not working

Using this repository, no errors were produced on my end, maybe try again?

**Comment by LucasB25** [comment]
![image](https://github.com/shipgirlproject/Shoukaku/assets/50886682/a6138da3-42d6-437e-b4f7-6288ec98ceb5)

It seems to be good it remains that this concern

**Comment by 0t4u** [comment]
That would be an issue with your code, and not the fault of the types

**Comment by LucasB25** [comment]
> > I'm really sorry, I missed the `emit`... I'll fix it when I can.
> 
> I do not understand despite your reverse I still have this error after updating the files ![image](https://private-user-images.githubusercontent.com/50886682/344274005-db47cf73-cb47-4021-817c-13949b95590f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzcxMjksIm5iZiI6MTcxOTY3NjgyOSwicGF0aCI6Ii81MDg4NjY4Mi8zNDQyNzQwMDUtZGI0N2NmNzMtY2I0Ny00MDIxLTgxN2MtMTM5NDliOTU1OTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE2MDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMGNhZDFjOGExNmJkN2Q5ODQ5MGU5ZmU0NmMyZjhlZWVjZjU1MTE1ZDBhNmFkYTk5NWM5MTVjZTBhOThlZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D8ujS8wzV-lgM8eufU-SLS7K62c2YytWypQswQGZdsA)

here we go again

**Comment by EvilG-MC** [comment]
> ![image](https://private-user-images.githubusercontent.com/50886682/344409750-d417a928-f24c-4244-ae7c-e6cedd231cfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2Nzk0MjEsIm5iZiI6MTcxOTY3OTEyMSwicGF0aCI6Ii81MDg4NjY4Mi8zNDQ0MDk3NTAtZDQxN2E5MjgtZjI0Yy00MjQ0LWFlN2MtZTZjZWRkMjMxY2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE2Mzg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNmEyNThmOTk2ZjQwMTkzNmVlMjY2YWVhYzE5MTZjYzAyZDA2ZjNlNDljNGE1MmZjYTI4ZjgxNjQ1YjZlMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PxnJ41wK_GeT19J66UtVdpFbC-0gJBYU5fM87T7368o)
> 
> here we go again It is the Typescript package updates that recreated the error

Did you try using the github version?

**Comment by LucasB25** [comment]
`github:shipgirlproject/Shoukaku` ?

**Comment by EvilG-MC** [comment]
> `github:shipgirlproject/Shoukaku` ?

Yep

**Comment by LucasB25** [comment]
ah nope

**Comment by EvilG-MC** [comment]
I'm going to assume that worked

**Comment by LucasB25** [comment]
I'm going to assume that worked
