### ISSUE TITLE
new update break wavemusic and it back to work if i install old shoukaku version 

### ISSUE THREAD

**Issue by furinaxpgn** [shipgirlproject/Shoukaku#192]
<rejected> RestError: Bad Request
      at Rest.fetch (/home/rainy75/WaveMusic/node_modules/shoukaku/dist/index.js:998:13)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Player.update (/home/rainy75/WaveMusic/node_modules/shoukaku/dist/index.js:717:5) {
    timestamp: 1724431493054,
    status: 400,
    error: 'Bad Request',
    trace: undefined,
    path: '/v4/sessions/l16754y401q7o1xo/players/1191613694996664350'
  }
} reason: RestError: Bad Request
    at Rest.fetch (/home/rainy75/WaveMusic/node_modules/shoukaku/dist/index.js:998:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Player.update (/home/rainy75/WaveMusic/node_modules/shoukaku/dist/index.js:717:5) {
  timestamp: 1724431493054,
  status: 400,
  error: 'Bad Request',
  trace: undefined,
  path: '/v4/sessions/l16754y401q7o1xo/players/1191613694996664350'

**Comment by Ninja156** [comment]
i have the same issue

**Comment by Deivu** [comment]
Any more info related about the issue, what is the options you passed, and when did it happen

**Comment by GOLD3NICK1** [comment]
I have the same problem, it was working yesterday but as of today it no longer works I tried to update with this new version but could not solve anything, I too have the same error on wavemusic as @furinaxpgn

**Comment by Deivu** [comment]
Since no one answered my question, try installing commit 9d5588e and see if that fixes your issue. I never had this issue on 4.1.0 with secure and resume turned to on.

**Comment by GOLD3NICK1** [comment]
I have this problem in the javascript version https://www.npmjs.com/package/shoukaku?activeTab=readme  
do you know how i can solve it there ? the error is:

  error     Unhandled Rejection at: Promise {
  <rejected> RestError: Bad Request
      at Rest.fetch (/home/container/node_modules/shoukaku/dist/index.js:998:13)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Player.update (/home/container/node_modules/shoukaku/dist/index.js:717:5) {
    timestamp: 1724507630832,
    status: 400,
    error: 'Bad Request',
    trace: undefined,
    path: '/v4/sessions/6sypyav6jx1nwspr/players/1125350112617570386'
  }
} reason: RestError: Bad Request
    at Rest.fetch (/home/container/node_modules/shoukaku/dist/index.js:998:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Player.update (/home/container/node_modules/shoukaku/dist/index.js:717:5) {
  timestamp: 1724507630832,
  status: 400,
  error: 'Bad Request',
  trace: undefined,
  path: '/v4/sessions/6sypyav6jx1nwspr/players/1125350112617570386'
}

**Comment by EvilG-MC** [comment]
> Since no one answered my question, try installing commit [9d5588e](https://github.com/shipgirlproject/Shoukaku/commit/9d5588e950f8b8cbe3cdd5386a275943ff6fdba1) and see if that fixes your issue. I never had this issue on 4.1.0 with secure and resume turned to on.

I have tested shoukaku in the version prior to this commit with my own implementation and it did not give me that error, perhaps it is a third-party factor

**Comment by Deivu** [comment]
Resume option set to false 
![image1](https://safe.saya.moe/bbMMMEaxlgw5.png)

No errors throwing
![result1](https://safe.saya.moe/2b2IXmVDUDyx.png)

Clearly you can see resume by Lavalink is false (since resume option is set to false), means we received a new session id for this session, but didn't get a 400 bad request, means the session id is correct.

When resume option is set to true, I'm pretty sure that also don't have any issues since i run that configuration in prod

**Comment by Deivu** [comment]
> > Since no one answered my question, try installing commit [9d5588e](https://github.com/shipgirlproject/Shoukaku/commit/9d5588e950f8b8cbe3cdd5386a275943ff6fdba1) and see if that fixes your issue. I never had this issue on 4.1.0 with secure and resume turned to on.
> 
> I have tested shoukaku in the version prior to this commit with my own implementation and it did not give me that error, perhaps it is a third-party factor

This also further solidifies that this isn't an issue with shoukaku, so it's better to report it to wavelink repo, or don't update your shoukaku instance to 4.1.x and above.

Since my implementation did not also error, means this isn't a breaking change most likely and is backwards compatible.
