### ISSUE TITLE
Problem with playing links

### ISSUE THREAD

**Issue by infnibor** [shipgirlproject/Shoukaku#193]
Hey, 
I'm using your client and I have this question, well in recent days I noticed a problem of incorrect decoding of links from yt using your client and here is my question, because I managed to locate the problem - would it be possible for you in the client to support the method of reproducing songs using also a method such as in this repository https://github.com/ray-1337/youtube-discord-embed.

**Comment by Deivu** [comment]
Any example code that I can use to reproduce?

**Comment by infnibor** [comment]
> Any example code that I can use to reproduce?

E.g. using [lavamusic](https://github.com/appujet/lavamusic), which uses your client using setupchanel, when I paste a simple link to a youtube video e.g. https://youtu.be/Xz_9BFxDdyA?feature=shared it converts it and passes it to the lavalink server in the format https://yt.cdn.13373333.one/watch?v=Xz_9BFxDdyA&dearrow?feature=shared. I have managed to establish that this strange link is some sort of redirect embed (link to the repo above) and would it be possible to support in the client the handling of these links. 


https://github.com/user-attachments/assets/351d3144-1da2-4985-98fd-998a2b48e338

**Comment by LucasB25** [comment]
> Any example code that I can use to reproduce?

This concern concerns some countries
I made the same request to my lavalink no worries so it is a global problem for many users making requests from certain countries
