### ISSUE TITLE
Bad Request Error 400

### ISSUE THREAD

**Issue by thenewgessiko** [shipgirlproject/Shoukaku#195]
In the console, at every playback request I find myself via youtube, spotify, and soundcloud it gives me bad request error 400 why?

**Comment by Deivu** [comment]
Check: https://guide.shoukaku.shipgirl.moe/guides/3-common/#playing-a-track-and-changing-a-playback-option

**Comment by thenewgessiko** [comment]
![20240830_181328](https://github.com/user-attachments/assets/1e701545-04e6-47db-a8f4-117ae230adb2)

**Comment by thenewgessiko** [comment]
> Check: https://guide.shoukaku.shipgirl.moe/guides/3-common/#playing-a-track-and-changing-a-playback-option

Look the photo! THANK!

**Comment by Deivu** [comment]
As I said, how about read the guide and correct your code based on that? This is also not the place where to ask for help

**Comment by thenewgessiko** [comment]
> As I said, how about read the guide and correct your code based on that? This is also not the place where to ask for help

Ok but RELAX BRUH ... I asked for help ... forget it, it's clear that you don't want to help a person ... thanks for your help even if you're not interested I thank you anyway.
