### ISSUE TITLE
Shoukaku Options Not Working

### ISSUE THREAD

**Issue by Aazann** [shipgirlproject/Shoukaku#201]
Since i updated to 4.1.1 version the shoukaku stops working i notice it while my userAgent was no more working.I asked few many developers they were having same issue.

**Comment by ErrorDoc404** [comment]
Same after updating to 4.1.1 the shoukaku options stop working 
![image](https://github.com/user-attachments/assets/d56bb761-e402-4f90-ab15-75002e80383a)

**Comment by 0t4u** [comment]
This is actually intended behavior. Here, Lavalink is printing the Client-Name header, not the User-Agent header. According to Lavalink documentation, Client-Name refers to information about the *client library* (in this case, shoukaku).

ref: https://lavalink.dev/api/websocket.html#websocket-api
